HarryPotter= {
        "Harry Potter": "Harry James Potter is the titular protagonist of J. K. Rowling's Harry Potter series. The majority of the books' plot covers seven years in the life of the orphan Potter, who, on his eleventh birthday, learns he is a wizard. Thus, he attends Hogwarts School of Witchcraft and Wizardry to practice magic under the guidance of the kindly headmaster Albus Dumbledore and other school professors along with his best friends Ron Weasley and Hermione Granger. Harry also discovers that he is already famous throughout the novel's magical community, and that his fate is tied with that of Lord Voldemort, the internationally feared Dark Wizard and murderer of his parents, Lily and James. The film and book series revolve around Harry's struggle to adapt to the wizarding world and defeat Voldemort. Harry is considered a fictional icon and has been described by many critics, readers, and audiences as one of the greatest literary and film characters of all time.",
        "Hermione Granger": "Hermione Jean Granger (/hɜːrˈmaɪ.əni ˈdʒiːn ˈɡreɪndʒər/) is a fictional character in J. K. Rowling's Harry Potter series. She first appears in Harry Potter and the Philosopher's Stone, as a new student on her way to Hogwarts. After Harry and Ron save her from a mountain troll in the girls' toilets, she becomes best friends with them and often uses her quick wit, deft recall, and encyclopaedic knowledge to help them. Rowling has stated that Hermione resembles herself at a younger age, with her insecurity and fear of failure.[1] The character has received immense acclaim and popularity, and was voted the best female character in a poll conducted amongst Hollywood professionals by The Hollywood Reporter in 2016.[2]",
        "Ron Weasley": "Ronald Bilius 'Ron' Weasley is a fictional character in J. K. Rowling's Harry Potter series. His first appearance was in the first book of the series, Harry Potter and the Philosopher's Stone as the best friend of Harry Potter and Hermione Granger. He is a member of the Weasley family, a pure blood family, who reside in 'The burrow' outside Ottery St. Catchpole. Along with Harry and Hermione, he is a member of the Gryffindor house. Ron is present in most of the action throughout the series." ,  
        "Lord Voldemort": '''Lord Voldemort (/ˈvoʊldəmɔːr/,[1][2] /-mɔːrt/ in the films; born Tom Marvolo Riddle) is a fictional character and the main antagonist in J. K. Rowling's series of Harry Potter novels. Voldemort first appeared in Harry Potter and the Philosopher's Stone, which was released in 1997. Voldemort appears either in person or in flashbacks in each book and its film adaptation in the series, except the third, Harry Potter and the Prisoner of Azkaban, where he is only mentioned.
    Voldemort is the archenemy of Harry Potter, who according to a prophecy has "the power to vanquish the Dark Lord". Nearly every witch or wizard dares not utter his unmentionable name, and refers to him instead with such expressions as "You-Know-Who", "He-Who-Must-Not-Be-Named" or "the Dark Lord". Voldemort's obsession with blood purity signifies his aim to rid the wizarding world of Muggle (non-magical) heritage and to conquer both worlds, Muggle and wizarding, to achieve pure-blood dominance. Through his mother's family, he is the last descendant of wizard Salazar Slytherin,[3] one of the four founders of Hogwarts School of Witchcraft and Wizardry. He is the leader of the Death Eaters, a group of evil wizards and witches dedicated to ridding the Wizarding World of Muggles and establishing Voldemort as its supreme ruler.''',
        "Albus Dumbledore": '''Professor Albus Percival Wulfric Brian Dumbledore[1] is a fictional character in J. K. Rowling's Harry Potter series.  For most of the series, he is the headmaster of the wizarding school Hogwarts. As part of his backstory, it is revealed that he is the founder and leader of the Order of the Phoenix, an organisation dedicated to fighting Lord Voldemort.
    Dumbledore is portrayed by Richard Harris in the film adaptations of Harry Potter and the Philosopher's Stone and Harry Potter and the Chamber of Secrets. After Harris' death, Michael Gambon portrayed Dumbledore for all of the remaining Harry Potter films. Jude Law will portray Dumbledore in Fantastic Beasts: The Crimes of Grindelwald.[2]
    Rowling stated she chose the name Dumbledore, which is a dialectal word for "bumblebee",[3] because of Dumbledore's love of music: she imagined him walking around "humming to himself a lot".[4][5]'''}
while True:
    n=input("choose a character from the books Harry Potter:").title()
    if n in HarryPotter:
       print(HarryPotter[n])
    elif n not in HarryPotter:
       print("Thats not a character")
    m=input("Search more?")
    if m=="yes":
       continue
    elif m=="no":
       break
    
   
